[seestar-overlay]
ontop
no-border
geometry=426x240-20-20
hwdec=no
vo=x11
rtsp-transport=tcp
keep-open=yes
osd-msg1=Waiting for Seestar...
force-window=yes
idle=yes
no-osc
msg-level=all=no
input-ipc-server=/tmp/mpv-seestar
